"""Initial schema

Revision ID: 2d49e186a972
Revises: 
Create Date: 2026-07-04 04:44:06.340904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d49e186a972'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('target_bank', sa.String(length=100), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('source_app', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_domain'), 'analytics', ['domain'], unique=False)
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=100), nullable=False),
    sa.Column('target_brand', sa.String(length=100), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('domains_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_name'), 'campaigns', ['campaign_name'], unique=True)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('registered_at', sa.String(length=100), nullable=True),
    sa.Column('ssl_issuer', sa.String(length=255), nullable=True),
    sa.Column('ssl_valid', sa.Boolean(), nullable=True),
    sa.Column('ssl_expired', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('password_forms', sa.Integer(), nullable=True),
    sa.Column('login_forms', sa.Integer(), nullable=True),
    sa.Column('iframe_count', sa.Integer(), nullable=True),
    sa.Column('favicon_hash', sa.String(length=255), nullable=True),
    sa.Column('bank_brand', sa.String(length=100), nullable=True),
    sa.Column('brand_confidence', sa.Float(), nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('feed_version', sa.String(length=50), nullable=True),
    sa.Column('heuristic_version', sa.String(length=50), nullable=True),
    sa.Column('intel_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_domain'), 'intelligence', ['domain'], unique=True)
    op.create_index(op.f('ix_intelligence_id'), 'intelligence', ['id'], unique=False)
    op.create_table('phishing_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_domains_domain'), 'phishing_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_phishing_domains_id'), 'phishing_domains', ['id'], unique=False)
    op.create_table('safe_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('list_version', sa.String(length=50), nullable=True),
    sa.Column('generated_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safe_domains_domain'), 'safe_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_safe_domains_id'), 'safe_domains', ['id'], unique=False)
    op.create_index(op.f('ix_safe_domains_rank'), 'safe_domains', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safe_domains_rank'), table_name='safe_domains')
    op.drop_index(op.f('ix_safe_domains_id'), table_name='safe_domains')
    op.drop_index(op.f('ix_safe_domains_domain'), table_name='safe_domains')
    op.drop_table('safe_domains')
    op.drop_index(op.f('ix_phishing_domains_id'), table_name='phishing_domains')
    op.drop_index(op.f('ix_phishing_domains_domain'), table_name='phishing_domains')
    op.drop_table('phishing_domains')
    op.drop_index(op.f('ix_intelligence_id'), table_name='intelligence')
    op.drop_index(op.f('ix_intelligence_domain'), table_name='intelligence')
    op.drop_table('intelligence')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_domain'), table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
